# 服务器配置
server: 
  port: 8080
  
server: 
  context-path: /datum

# 持久化及数据源配置
spring: 
  jpa: 
    open-in-view: true
    show-sql: true
    properties: 
      hibernate:
        format_sql: true
  h2: 
   console: 
    enabled: true
    path: /db-console
    settings:
      web-allow-others: true
         
   
datum: 
  datasource: 
    url: jdbc:h2:file:./db/datum
    username: datum
    password: datum
    driver-class-name: org.h2.Driver
    validation-query: SELECT 1
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-interval: 10000
    time-between-eviction-runs-millis: 10000
    min-evictable-idle-time-millis: 10000
    remove-abandoned: true
    remove-abandoned-timeout: 60
    test-on-borrow: true
    test-while-idle: true
