
-- 客户基本信息
DROP TABLE IF EXISTS CUST_BASIC_INFO;
CREATE TABLE CUST_BASIC_INFO(
CUS_ID CHAR(10) NOT NULL PRIMARY KEY,--客户ID
NAME VARCHAR(200) NOT NULL,--客户名称
GENDER CHAR(1) NOT NULL,--客户姓别 'F':女 'M':男  
BRANCH CHAR(11) NOT NULL,--归属分行
ID_TYPE CHAR(2) NOT NULL,--证件类型
ID_NO VARCHAR(50) NOT NULL,--证件号码
ADDRESS VARCHAR(200), --住址
MOBILE VARCHAR(20)--手机号
);

-- 账户信息
DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT(
ACCOUNT_NO VARCHAR(20) NOT NULL PRIMARY KEY,--账号
CUS_ID CHAR(10),--客户号
OPEN_DATE DATE,--开户日期
BALANCE DECIMAL(20,2)--账户余额
);

-- 银行传票流水
DROP TABLE IF EXISTS BANK_VOUCHER;

CREATE TABLE BANK_VOUCHER (
VOUCHER_SEQ CHAR(20) NOT NULL PRIMARY KEY,--传票序列号
TXN_CDE CHAR(5) NOT NULL,--交易码
ACCOUNT_NO VARCHAR(20) NOT NULL,--账号
TXN_DATE DATE,--交易日期
AMT DECIMAL(20,2),--交易金额   'D':借 'C':贷  
DC_FLAG CHAR(1),--借贷标识
REMARK VARCHAR(500)--备注
);
